/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tortue.Vue;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.Iterator;
import tortue.Controleur.Dessin.ControleurDessin;
import tortue.Model.Dessin.AbstractTortue;
import tortue.Model.Dessin.Segment;

/**
 *
 * @author Arnaud
 */
public class FeuilleDessin extends javax.swing.JPanel {

    /**
     * Creates new form FeuilleDessin
     */
    private Dimension m_dim;
    
    public FeuilleDessin() 
    {
        initComponents();
    }

    public Dimension getdim() 
    {
        return m_dim;
    }
    
    public void paintComponent(Graphics g) 
    {
        super.paintComponent(g);

        Color c = g.getColor();

        m_dim = getSize();
        g.setColor(Color.white);
        g.fillRect(0,0,m_dim.width, m_dim.height);
        g.setColor(c);

        showTurtles(g);
    }
	
    public void showTurtles(Graphics g) 
    {         
        for(Iterator it = ControleurDessin.getTabTortue().iterator();it.hasNext();)
        {
            AbstractTortue t = (AbstractTortue)it.next();
            g.setColor(Color.BLACK);

            for(Iterator it2 = t.getTrace().iterator(); it2.hasNext();)
            {
                Segment s = (Segment)it2.next();
                g.drawLine(s.getStart().x, s.getStart().y, s.getEnd().x, s.getEnd().y);
            }           
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
